version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=healdb
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  backend:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
volumes:
  db:
