spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        type: trace
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:mysql://${{secrets.RDS_URL}}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${{secrets.RDS_USER}}
    password: ${{secrets.RDS_PASSWORD}}

  flyway:
    url: jdbc:mysql://${{secrets.RDS_URL}}
    user: ${{secrets.RDS_USER}}
    password: ${{secrets.RDS_PASSWORD}}
    baselineOnMigrate: true