spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        type: trace
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    url: hmsrdstrial.cqunz6ixnkor.ap-southeast-1.rds.amazonaws.com
    username: HMSAdmin
    password: HMSAdmin

  flyway:
    url: hmsrdstrial.cqunz6ixnkor.ap-southeast-1.rds.amazonaws.com
    user: HMSAdmin
    password: HMSAdmin
    baselineOnMigrate: true