spring:
  data:
    mongodb:
      uri: mongodb://user:pass@localhost:27017/healdb?authSource=admin
      uuid-representation: standard
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        type: trace
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:mysql://heal-db.c8cer7bgfoe7.ap-southeast-1.rds.amazonaws.com/healdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: {{secrets}}
    password: {{secrets}}

  flyway:
    url: jdbc:mysql://heal-db.c8cer7bgfoe7.ap-southeast-1.rds.amazonaws.com/healdb
    user: {{secrets}}
    password: {{secrets}}
    baselineOnMigrate: true

secEnvConf:
  enableLoginGuard: false
