spring:
  address: localhost
  data:
    mongodb:
      uri: mongodb://user:pass@localhost:27017/healdb?authSource=admin
      uuid-representation: standard

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        type: trace
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:mysql://localhost:3306/healdb
    username: root
    password: 123456

  flyway:
    url: jdbc:mysql://localhost:3306/healdb
    user: root
    password: 123456
    baselineOnMigrate: true

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG