spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        type: trace
        show_sql: true
        format_sql: true
        use_sql_comments: true
      logging:
        level:
          org.hibernate.SQL: DEBUG
          org.hibernate.type: TRACE
  datasource:
    url: jdbc:mysql://localhost:3306/healdb
    username: root
    password: password

  flyway:
    url: jdbc:mysql://localhost:3306/healdb
    user: root
    password: password
    baselineOnMigrate: true