name: End to End CI/CD workflow for Java Applicaton with Maven, Sonar and k8s Intergation
on:
    # Trigger analysis when pushing in master or pull requests, and when creating
    # a pull request. 
    push:
      branches:
        - Backenddevops
    #pull_request:
        #types: [opened, synchronize, reopened]
  
      
jobs:
    build:
       runs-on: self-hosted
        
       steps:
        - name: Checkout code
          uses: actions/checkout@v3
        
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: 17
            distribution: 'temurin'
            cache: maven
        
        - name: maven target # change accordingly
          run: ./mvnw clean spring-boot:run -Dspring-boot.run.profiles=dev

    sonarqube:
      name: SonarQube Trigger
      runs-on: self-hosted
      steps:
      - name: Checking out
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      
      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.2.0
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}
          projectKey: BackendCodeScan


      
      
