name: Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, reopened, review_requested, edited, synchronize]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Run tests
        run: chmod +x ./mvnw && ./mvnw clean test
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
